[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build && node build-content-json.js"

# NOTE: The following plugins were removed as they were causing build failures
# These plugins don't appear to be available in the npm registry:
# - @netlify/plugin-functions-core
# - @netlify/plugin-local-install-core
# If you need these plugins, they must be properly installed or configured in the Netlify UI

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = """
      default-src 'self' https://*.netlify.app;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: https://*.netlify.app https://*.mathigon.org https://*.google-analytics.com https://www.googletagmanager.com https://overbridgenet.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: blob: https://*.netlify.app https://*.mathigon.org https://*.render.com https://api.dicebear.com https://*.google-analytics.com https://www.googletagmanager.com;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' blob: data: https://*.netlify.app https://*.mathigon.org https://*.render.com https://kha-boom-backend.onrender.com https://fonts.googleapis.com https://fonts.gstatic.com https://api.dicebear.com https://*.google-analytics.com https://www.googletagmanager.com https://overbridgenet.com;
      object-src 'none';
      frame-src https://player.vimeo.com https://www.youtube.com https://*.mathigon.org;
      worker-src 'self' blob:;
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
    """

# Content-Type headers for different file types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.jsx?*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/data:text/jsx;base64*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Add additional rules for Mathigon assets
[[headers]]
  for = "/mathigon/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/mathigon/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# More specific content type rule for JSON files - most important fix
[[headers]]
  for = "/mathigon/content/*/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin: "*"

# More general content rule
[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=86400"

# Add special handling for fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Content-Type = "font/woff"
    Cache-Control = "public, max-age=31536000"

# Add HTML content type
[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, no-cache"

# Force service worker to be served as JavaScript
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"
    
# For diagnostic script
[[headers]]
  for = "/mathigon-test.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate" 