[build]
  command = "npm install && npm run build"
  publish = "dist"

[context.production.environment]
  VITE_API_BASE = "https://kha-boom-backend.onrender.com"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for proper MIME types and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
