[build]
  command = "npm ci && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- ."

[build.environment]
  NODE_VERSION = "18.17.0"

# Production context: all deploys from the main branch will inherit these settings
[context.production.environment]
  VITE_API_BASE = "https://kha-boom-backend.onrender.com"
  NODE_ENV = "production"
  VITE_SITE_URL = "https://khaboom.netlify.app"

# Branch deploy context: all deploys that aren't from a pull request or from the main branch
[context.branch-deploy.environment]
  VITE_API_BASE = "https://kha-boom-backend-staging.onrender.com"
  NODE_ENV = "staging"

# Development context: deploys from branches that aren't main
[context.dev.environment]
  VITE_API_BASE = "http://localhost:10000"
  NODE_ENV = "development"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for proper MIME types and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = """
      default-src 'self';
      script-src  'self' 'unsafe-inline' 'unsafe-eval' data: blob: https://www.google-analytics.com;
      style-src   'self' 'unsafe-inline' https://fonts.googleapis.com;
      connect-src 'self' https://kha-boom-backend.onrender.com https://kha-boom-backend-staging.onrender.com https://fonts.googleapis.com https://fonts.gstatic.com https://api.dicebear.com https://www.google-analytics.com https://*.mongodb.net http://localhost:* https://*.netlify.app https://overbridgenet.com;
      font-src    'self' https://fonts.gstatic.com data:;
      img-src     'self' data: blob: https://api.dicebear.com https://kha-boom-backend.onrender.com https://*.netlify.app;
      manifest-src 'self'
    """

# Content types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    
[[headers]]
  for = "/*.module.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/main.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/course.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/dashboard.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Add specific header for module scripts
[[headers]]
  for = "/*.module.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
