siteName: KhaBoom
description: Interactive learning platform
domain: khaboom.netlify.app
apiBase: https://kha-boom-backend.onrender.com

privacyURL: https://khaboom.netlify.app/privacy
banner: KhaBoom Learning Platform
locales: [en, ar, cn, de, es, fr, hi, hr, it, ja, pt, ro, ru, sv, tr, vi]

search:
  enabled: true
  indexSize: 5000
  suggestionCount: 10

footer:
  rows:
    - links:
        - title: GitHub
          url: https://github.com/joinquit3110/KhaBoom
        - title: About
          url: https://khaboom.netlify.app/about
  copyright: © KhaBoom Learning Platform, 2025

social:
  facebook: {}
  twitter: {}

courses:
  showLocked: false
  revealAll: false
  audio: true
  progressTracking: true
  mongodb: true

tutor:
  enabled: true
  personalizedFeedback: true

dbConfig:
  uri: mongodb+srv://joinquit:31102004@khaboomdb.cqugkeo.mongodb.net/?retryWrites=true&w=majority&appName=KhaBoomDB
  trackProgress: true
  saveUserData: true
