[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- frontend/."

[build.environment]
  NODE_VERSION = "18.17.0"

# Production context: all deploys from the main branch will inherit these settings
[context.production.environment]
  VITE_API_BASE = "https://kha-boom-backend.onrender.com"
  NODE_ENV = "production"
  VITE_SITE_URL = "https://khaboom.netlify.app"
  MONGODB_URI = "mongodb+srv://<username>:<password>@<cluster-address>/khaboom?retryWrites=true&w=majority"

# Branch deploy context: all deploys that aren't from a pull request or from the main branch
[context.branch-deploy.environment]
  VITE_API_BASE = "https://kha-boom-backend-staging.onrender.com"
  NODE_ENV = "staging"
  MONGODB_URI = "mongodb+srv://<username>:<password>@<cluster-address>/khaboom-staging?retryWrites=true&w=majority"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Special MongoDB proxy for database health checks
[[redirects]]
  from = "/api/health/db"
  to = "https://kha-boom-backend.onrender.com/api/health/db"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS" 
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  }

# Auth endpoints proxy
[[redirects]]
  from = "/api/auth/*"
  to = "https://kha-boom-backend.onrender.com/api/auth/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  }

# Progress tracking proxy - critical for MongoDB
[[redirects]]
  from = "/api/progress/*"
  to = "https://kha-boom-backend.onrender.com/api/progress/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  }
  
# User profile proxy
[[redirects]]
  from = "/api/user/*"
  to = "https://kha-boom-backend.onrender.com/api/user/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  }

# General API proxy - catch all other API routes
[[redirects]]
  from = "/api/*"
  to = "https://kha-boom-backend.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  }

# Mathigon content redirects - placed AFTER API redirects but BEFORE the SPA redirect
[[redirects]]
  from = "/mathigon/*"
  to = "/mathigon/:splat"
  status = 200

# Add headers for proper MIME types and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.mathigon.org https://*.google-analytics.com https://www.googletagmanager.com https://overbridgenet.com;
      connect-src 'self' https://*.netlify.app https://*.mathigon.org https://*.render.com https://kha-boom-backend.onrender.com https://fonts.googleapis.com https://fonts.gstatic.com https://api.dicebear.com https://*.google-analytics.com https://www.googletagmanager.com https://overbridgenet.com https://*.mongodb.net https://*.mongodb-analytics.com;
      img-src 'self' data: blob: https://*.mathigon.org https://api.dicebear.com https://*.google-analytics.com https://www.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      object-src 'none';
      frame-src https://player.vimeo.com https://www.youtube.com https://*.mathigon.org;
      worker-src 'self' blob:;
      manifest-src 'self';
    """

# Content types for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/mathigon/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Content types for CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

# Course content files
[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/mathigon/content/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Redirect rules
[[redirects]]
  from = "/course/:id/*"
  to = "/:id/:splat"
  status = 301