[build]
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- frontend/."

[build.environment]
  NODE_VERSION = "18.17.0"

# Production context: all deploys from the main branch will inherit these settings
[context.production.environment]
  VITE_API_BASE = "https://kha-boom-backend.onrender.com"
  NODE_ENV = "production"
  VITE_SITE_URL = "https://khaboom.netlify.app"

# Branch deploy context: all deploys that aren't from a pull request or from the main branch
[context.branch-deploy.environment]
  VITE_API_BASE = "https://kha-boom-backend-staging.onrender.com"
  NODE_ENV = "staging" 